# Tutorial 3 - Python For Data Analysis 🐍

---

## Pandas

### *Table of Contents*

- Pandas 🐼
  - [Introduction](#intro)
  - [Exercice 1](#exercise-5) : Explore Pandas DataFrame basic functions
  - [Exercise 2](#exercise-6) : Explore traffic accidents vehicles

In [2]:
import pandas as pd
import numpy as np


## Pandas 🐼

<a name="intro">

### Introduction - Traffic Accidents Database
---

https://www.data.gouv.fr/fr/datasets/base-de-donnees-accidents-corporels-de-la-circulation/

For each personal injury accident, information describing the accident is entered by the law enforcement unit that intervened at the scene of the accident. These seizures are brought together in a sheet called the personal accident analysis report. All of these files constitute the national file of traffic accidents known as the "BAAC File" administered by the National Intermenstrual Road Safety Observatory "ONISR".

The databases, extracted from the BAAC file, list all of the bodily injury accidents occurring during a specific year in mainland France, in the overseas departments (Guadeloupe, Guyana, Martinique, Réunion and Mayotte since 2012) and in the other overseas territories (Saint-Pierre- et-Miquelon, Saint-Barthélemy, Saint-Martin, Wallis-et-Futuna, French Polynesia and New Caledonia; available only from 2019 in open data) with a simplified description. This includes accident location information, as entered as well as information regarding the characteristics of the accident and its location, the vehicles involved and their victims.

The databases from 2005 to 2019 are now annual and made up of 4 files (Characteristics - Locations - Vehicles - Users) in csv format.

Links to databases:
- https://www.data.gouv.fr/fr/datasets/r/be2191a6-a7cd-446f-a9fc-8d698688eb9e
- https://www.data.gouv.fr/fr/datasets/r/e4c6f4fe-7c68-4a1d-9bb6-b0f1f5d45526
- https://www.data.gouv.fr/fr/datasets/r/08b77510-39c4-4761-bf02-19457264790f
- https://www.data.gouv.fr/fr/datasets/r/96aadc9f-0b55-4e9a-a70e-c627ed97e6f7
   
SETUP : We’ll use vehicles database.

Import the data using pandas library.`pd.read_csv(url)`

In [41]:
voiture = pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/be2191a6-a7cd-446f-a9fc-8d698688eb9e")

<a name="exercise-5">

### Exercise 1 : Explore Pandas DataFrame basic functions
---

1) How many columns do we have in the DataFrame ? How many rows do we have ?

In [42]:
print("nb colonnes : ", voiture.shape[1])
print("nb lignes : ",voiture.shape[0])

nb colonnes :  9
nb lignes :  101924


2) What are the types of columns in the DataFrame ? Use `info()` function.

In [43]:
print(voiture.info())
#dtypes: float64(5), int64(3), object(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101924 entries, 0 to 101923
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   Num_Acc  101924 non-null  int64  
 1   senc     101852 non-null  float64
 2   catv     101924 non-null  int64  
 3   occutc   101924 non-null  int64  
 4   obs      101886 non-null  float64
 5   obsm     101874 non-null  float64
 6   choc     101913 non-null  float64
 7   manv     101917 non-null  float64
 8   num_veh  101924 non-null  object 
dtypes: float64(5), int64(3), object(1)
memory usage: 7.0+ MB
None


3) Calculate the mean of numeric columns.

In [44]:
print("the means of the numeric columns are:\n",voiture.mean(numeric_only=True))

the means of the numeric columns are:
 Num_Acc    2.016000e+11
senc       1.041433e+00
catv       1.204036e+01
occutc     7.061144e-02
obs        8.706299e-01
obsm       1.594941e+00
choc       2.857947e+00
manv       5.703896e+00
dtype: float64


4) Calculate the maximum and minimum value of numeric column.

In [45]:
print("the max value for each numeric column is:\n",voiture.max(numeric_only=True))
print("the min value for each numeric column is:\n",voiture.min(numeric_only=True))
    

the max value for each numeric column is:
 Num_Acc    2.016001e+11
senc       2.000000e+00
catv       9.900000e+01
occutc     3.000000e+02
obs        1.600000e+01
obsm       9.000000e+00
choc       9.000000e+00
manv       2.400000e+01
dtype: float64
the min value for each numeric column is:
 Num_Acc    2.016000e+11
senc       0.000000e+00
catv       1.000000e+00
occutc     0.000000e+00
obs        0.000000e+00
obsm       0.000000e+00
choc       0.000000e+00
manv       0.000000e+00
dtype: float64


5) Use `describe()` function, what can you observe ?

In [46]:
voiture.describe()

Num_Acc           senc           catv         occutc  \
count  1.019240e+05  101852.000000  101924.000000  101924.000000   
mean   2.016000e+11       1.041433      12.040363       0.070611   
std    1.711804e+04       0.747403      11.028127       2.221603   
min    2.016000e+11       0.000000       1.000000       0.000000   
25%    2.016000e+11       0.000000       7.000000       0.000000   
50%    2.016000e+11       1.000000       7.000000       0.000000   
75%    2.016000e+11       2.000000      10.000000       0.000000   
max    2.016001e+11       2.000000      99.000000     300.000000   

                 obs           obsm           choc           manv  
count  101886.000000  101874.000000  101913.000000  101917.000000  
mean        0.870630       1.594941       2.857947       5.703896  
std         2.931908       1.145935       2.476565       7.042847  
min         0.000000       0.000000       0.000000       0.000000  
25%         0.000000       1.000000       1.000000       1.000000  
50%         0.000000       2.000000       2.000000       1.000000  
75%         0.000000       2.000000       4.000000      13.000000  
max        16.000000       9.000000       9.000000      24.000000

Answer :the description of the dataframe, it shows the count, mean, std, min, max, 25%, 50%, 75% for each column

6) Display the first 30 values, then last 30.

In [47]:
print(voiture.head(30))
print(voiture.tail(30))

         Num_Acc  senc  catv  occutc   obs  obsm  choc  manv num_veh
0   201600000001   0.0     7       0   0.0   0.0   1.0   1.0     B02
1   201600000001   0.0     2       0   0.0   0.0   7.0  15.0     A01
2   201600000002   0.0     7       0   6.0   0.0   1.0   1.0     A01
3   201600000003   0.0     7       0   0.0   1.0   6.0   1.0     A01
4   201600000004   0.0    32       0   0.0   0.0   1.0   1.0     B02
5   201600000004   0.0     7       0   0.0   0.0   8.0  15.0     A01
6   201600000005   0.0    30       0   0.0   2.0   1.0  15.0     B02
7   201600000005   0.0     7       0   0.0   2.0   3.0   1.0     A01
8   201600000006   0.0     7       0   0.0   1.0   1.0   1.0     A01
9   201600000007   1.0    30       0   0.0   0.0   3.0  15.0     A01
10  201600000007   1.0     7       0   0.0   2.0   2.0  17.0     B02
11  201600000008   0.0     7       0   0.0   2.0   2.0   1.0     B02
12  201600000008   0.0     7       0   0.0   2.0   3.0  13.0     A01
13  201600000009   0.0     7      

<a name="exercise-6">

### Exercise 2 : Explore traffic accidents vehicles
---

Read the documentation to understand the meanings of each column.

Documentation: https://www.data.gouv.fr/fr/datasets/r/6cade01c-f69d-4779-b0a4-20606069888f

1) Then display the column names and rename it with the names of your choice. For the following questions, we use these column names:
```
[
"Num_Acc", "sens_de_Circulation", "catV", "nb_occupants", "obstacle_fixe", "obstacle_mobile", "choc", "manoeuvre" , "num_vehicule"
]
```

In [48]:
print(voiture.columns)
voiture.columns = ["Num_Acc", "sens_de_Circulation", "catV","nb_occupants", "obstacle_fixe", "obstacle_mobile", "choc", "manoeuvre" , "num_vehicule" ]
print(voiture.columns)

Index(['Num_Acc', 'senc', 'catv', 'occutc', 'obs', 'obsm', 'choc', 'manv',
       'num_veh'],
      dtype='object')
Index(['Num_Acc', 'sens_de_Circulation', 'catV', 'nb_occupants',
       'obstacle_fixe', 'obstacle_mobile', 'choc', 'manoeuvre',
       'num_vehicule'],
      dtype='object')


2) Get the number of null values by column. Then, display its proportion in the DataFrame.
For example : 0.08% of col_1 are null

In [49]:
print(voiture.isnull().sum())
print(voiture.isna().sum()*100/len(voiture))

Num_Acc                 0
sens_de_Circulation    72
catV                    0
nb_occupants            0
obstacle_fixe          38
obstacle_mobile        50
choc                   11
manoeuvre               7
num_vehicule            0
dtype: int64
Num_Acc                0.000000
sens_de_Circulation    0.070641
catV                   0.000000
nb_occupants           0.000000
obstacle_fixe          0.037283
obstacle_mobile        0.049056
choc                   0.010792
manoeuvre              0.006868
num_vehicule           0.000000
dtype: float64


#### Exploratory Data Analysis - Filters

3) Select `obstacle fixe` column, what is the type of returned value ?

In [51]:
print(voiture[["obstacle_fixe"]])

        obstacle_fixe
0                 0.0
1                 0.0
2                 6.0
3                 0.0
4                 0.0
...               ...
101919            0.0
101920            0.0
101921            0.0
101922            0.0
101923            0.0

[101924 rows x 1 columns]


4) Convert the returned value to a NumPy array

In [52]:
obstacle_fixe_np = np.array(voiture["obstacle_fixe"])
obstacle_fixe_np = obstacle_fixe_np[~np.isnan(obstacle_fixe_np)]

5) Compute the maximum value of the NumPy array

In [53]:
print(obstacle_fixe_np.max())

16.0


6) Select `catV` & `sens_de_Circulation columns together

In [55]:
multcoll = voiture[["sens_de_Circulation", "catV"]]
print(multcoll)

        sens_de_Circulation  catV
0                       0.0     7
1                       0.0     2
2                       0.0     7
3                       0.0     7
4                       0.0    32
...                     ...   ...
101919                  1.0    30
101920                  2.0    30
101921                  1.0    30
101922                  1.0     2
101923                  2.0     7

[101924 rows x 2 columns]


7) Select all the columns containing ‘obstacle’ in their name

In [16]:
filtcoll = voiture.filter(like="obstacle")
print(filtcoll)

        obstacle_fixe  obstacle_mobile
0                 0.0              0.0
1                 0.0              0.0
2                 6.0              0.0
3                 0.0              1.0
4                 0.0              0.0
...               ...              ...
101919            0.0              2.0
101920            0.0              2.0
101921            0.0              2.0
101922            0.0              2.0
101923            0.0              2.0

[101924 rows x 2 columns]


8) Select all rows with null values for 'sens_de_Circulation' column

In [56]:
sens_de_Circulation = voiture["sens_de_Circulation"]
nullrows = sens_de_Circulation[sens_de_Circulation.isnull()]
print(nullrows)

4153    NaN
4504    NaN
8407    NaN
12686   NaN
14845   NaN
         ..
74516   NaN
74612   NaN
74771   NaN
74814   NaN
84082   NaN
Name: sens_de_Circulation, Length: 72, dtype: float64


9) Sort the data frame using the accident number column

In [57]:
sortcoll = voiture.sort_values(by=["Num_Acc"])
print(sortcoll)

             Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
0       201600000001                  0.0     7             0            0.0   
1       201600000001                  0.0     2             0            0.0   
2       201600000002                  0.0     7             0            6.0   
3       201600000003                  0.0     7             0            0.0   
4       201600000004                  0.0    32             0            0.0   
...              ...                  ...   ...           ...            ...   
101919  201600059430                  1.0    30             0            0.0   
101920  201600059431                  2.0    30             0            0.0   
101921  201600059431                  1.0    30             0            0.0   
101922  201600059432                  1.0     2             0            0.0   
101923  201600059432                  2.0     7             0            0.0   

        obstacle_mobile  choc  manoeuvr

10) Sort the values using the accident number column, then the vehicle category column

In [58]:
sortcollalt = voiture.sort_values(by=["Num_Acc", "catV"])
print(sortcollalt)

             Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
1       201600000001                  0.0     2             0            0.0   
0       201600000001                  0.0     7             0            0.0   
2       201600000002                  0.0     7             0            6.0   
3       201600000003                  0.0     7             0            0.0   
5       201600000004                  0.0     7             0            0.0   
...              ...                  ...   ...           ...            ...   
101919  201600059430                  1.0    30             0            0.0   
101920  201600059431                  2.0    30             0            0.0   
101921  201600059431                  1.0    30             0            0.0   
101922  201600059432                  1.0     2             0            0.0   
101923  201600059432                  2.0     7             0            0.0   

        obstacle_mobile  choc  manoeuvr

11) Select the 4153rd row. Then select row having index '4153'. What is the difference between both?

In [59]:
sprow = voiture.iloc[4153]
sprowalt = voiture.loc[4153]
print(sprow)
print(sprowalt)
#the difference between getting the row with the index 4153 and the 4153rd row is
    # for the row with the index 4153 we get the row with the index 4153 and for the 4153rd row we get the row with
    # the index 4154

Num_Acc                201600002519
sens_de_Circulation             NaN
catV                              1
nb_occupants                      0
obstacle_fixe                   0.0
obstacle_mobile                 2.0
choc                            8.0
manoeuvre                       2.0
num_vehicule                    B02
Name: 4153, dtype: object
Num_Acc                201600002519
sens_de_Circulation             NaN
catV                              1
nb_occupants                      0
obstacle_fixe                   0.0
obstacle_mobile                 2.0
choc                            8.0
manoeuvre                       2.0
num_vehicule                    B02
Name: 4153, dtype: object


12)  Set Num_Acc as index

a. Make sure to use `inplace=True to save the value in the dataframe

b. Can you still get the row having index '4153'? Explain.
    No because the index is now the Num_Ac, so we can't get the row with the index 4153

c. Finally, Restore the index as it was before.

In [62]:
voiture.set_index("Num_Acc", inplace=True)
print(voiture)
voiture.reset_index(inplace=True)
print(voiture)

              sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
Num_Acc                                                                
201600000001                  0.0     7             0            0.0   
201600000001                  0.0     2             0            0.0   
201600000002                  0.0     7             0            6.0   
201600000003                  0.0     7             0            0.0   
201600000004                  0.0    32             0            0.0   
...                           ...   ...           ...            ...   
201600059430                  1.0    30             0            0.0   
201600059431                  2.0    30             0            0.0   
201600059431                  1.0    30             0            0.0   
201600059432                  1.0     2             0            0.0   
201600059432                  2.0     7             0            0.0   

              obstacle_mobile  choc  manoeuvre num_vehicule  
N

#### Exploratory Data Analysis - Queries

13) Select accident that have a vehicle number W23

In [63]:
print(voiture[voiture["num_vehicule"] == "W23"])

           Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
4073  201600002473                  2.0     7             0            0.0   

      obstacle_mobile  choc  manoeuvre num_vehicule  
4073              0.0   0.0        1.0          W23  


14) Select the top 5 accidents that caused the most damage

In [64]:
print(voiture.sort_values(by=["nb_occupants"], ascending=False).head(5))

            Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
9906   201600006084                  1.0    39           300            1.0   
40250  201600023870                  2.0    40           210            0.0   
40217  201600023850                  1.0    40           200            0.0   
40055  201600023760                  1.0    40           150            0.0   
40025  201600023740                  1.0    40           150            0.0   

       obstacle_mobile  choc  manoeuvre num_vehicule  
9906               0.0   1.0        0.0          B02  
40250              2.0   2.0        1.0          B01  
40217              2.0   3.0        1.0          A01  
40055              1.0   1.0        1.0          A01  
40025              2.0   2.0        1.0          B01  


15) Count the number of damaged vehicles, by vehicle category and number of occupants

In [65]:
print(voiture.groupby(["catV", "nb_occupants"]).count())


                   Num_Acc  sens_de_Circulation  obstacle_fixe  \
catV nb_occupants                                                
1    0                4705                 4698           4703   
2    0                3424                 3421           3422   
3    0                 436                  436            436   
7    0               64641                64585          64613   
10   0                5584                 5583           5582   
...                    ...                  ...            ...   
40   140                 1                    1              1   
     150                 2                    2              2   
     200                 1                    1              1   
     210                 1                    1              1   
99   0                 202                  202            202   

                   obstacle_mobile   choc  manoeuvre  num_vehicule  
catV nb_occupants                                                   
1  

16) From the previous result, select category vehicle '40', having '140' occupants

In [25]:
print(voiture.groupby(["catV", "nb_occupants"]).count().loc[40, 140])

Num_Acc                1
sens_de_Circulation    1
obstacle_fixe          1
obstacle_mobile        1
choc                   1
manoeuvre              1
num_vehicule           1
Name: (40, 140), dtype: int64


17) Calculate the number of occupants by vehicle category

In [26]:
print(voiture.groupby(["catV"]).sum()["nb_occupants"])

catV
1        0
2        0
3        0
7        0
10       0
13       0
14       0
15       0
16       0
17       0
20       0
21       0
30       0
31       0
32       0
33       0
34       0
35       0
36       0
37    2743
38    1385
39     522
40    2547
99       0
Name: nb_occupants, dtype: int64


18) Compute the number of damages per vehicle category

In [27]:
print(voiture.groupby(["catV"]).count()["Num_Acc"])

catV
1      4705
2      3424
3       436
7     64641
10     5584
13      406
14     1031
15      955
16       43
17      646
20       91
21      185
30     3953
31     2360
32     2087
33     8356
34     1515
35       20
36      137
37      737
38      229
39       31
40      150
99      202
Name: Num_Acc, dtype: int64


19) Select all the lines with a category vehicle between 37 and 40 inclusive. (These values correspond to public transport)

In [28]:
print(voiture[(voiture["catV"] >= 37) & (voiture["catV"] <= 40)])

             Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
129     201600000083                  1.0    39             0            0.0   
224     201600000148                  0.0    38             0            0.0   
278     201600000184                  0.0    37             0            1.0   
292     201600000193                  2.0    38             0            0.0   
522     201600000330                  0.0    39             1            0.0   
...              ...                  ...   ...           ...            ...   
101351  201600059075                  1.0    37             0            0.0   
101367  201600059084                  2.0    37             0            0.0   
101406  201600059103                  2.0    38             0            0.0   
101444  201600059125                  1.0    37             0            0.0   
101787  201600059339                  1.0    37             1            0.0   

        obstacle_mobile  choc  manoeuvr

20) Create a new column with a Boolean value, showing whether the accident happened in public transport or not

In [76]:
voiture["public_transport"] = voiture["catV"].apply(lambda x: True if 37 <= x <= 40 else False)
print(voiture)

             Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
0       201600000001                  0.0     7             0            0.0   
1       201600000001                  0.0     2             0            0.0   
2       201600000002                  0.0     7             0            6.0   
3       201600000003                  0.0     7             0            0.0   
4       201600000004                  0.0    32             0            0.0   
...              ...                  ...   ...           ...            ...   
101919  201600059430                  1.0    30             0            0.0   
101920  201600059431                  2.0    30             0            0.0   
101921  201600059431                  1.0    30             0            0.0   
101922  201600059432                  1.0     2             0            0.0   
101923  201600059432                  2.0     7             0            0.0   

        obstacle_mobile  choc  manoeuvr

21) Check that the new column is working well. For this, it is necessary to verify that the number of occupants in vehicles excluding public transport is equal to 0. Contrary to what we can see in the data in the other group.

In [71]:
print(voiture[voiture["public_transport"] == False]["nb_occupants"].sum())

0
0


22) Create a new dataframe, which contains only public transport accidents

In [77]:
public_transport = voiture[voiture["public_transport"] == True]
print(public_transport)

             Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
129     201600000083                  1.0    39             0            0.0   
224     201600000148                  0.0    38             0            0.0   
278     201600000184                  0.0    37             0            1.0   
292     201600000193                  2.0    38             0            0.0   
522     201600000330                  0.0    39             1            0.0   
...              ...                  ...   ...           ...            ...   
101351  201600059075                  1.0    37             0            0.0   
101367  201600059084                  2.0    37             0            0.0   
101406  201600059103                  2.0    38             0            0.0   
101444  201600059125                  1.0    37             0            0.0   
101787  201600059339                  1.0    37             1            0.0   

        obstacle_mobile  choc  manoeuvr

23) Obtain the average number of occupants by vehicle category, and sort the result

In [69]:
print(voiture.groupby(["catV"])["nb_occupants"].mean().sort_values())

catV
1      0.000000
36     0.000000
35     0.000000
34     0.000000
33     0.000000
32     0.000000
31     0.000000
30     0.000000
20     0.000000
21     0.000000
16     0.000000
15     0.000000
14     0.000000
13     0.000000
10     0.000000
7      0.000000
3      0.000000
2      0.000000
17     0.000000
99     0.000000
37     3.721845
38     6.048035
39    16.838710
40    16.980000
Name: nb_occupants, dtype: float64


24) Map the vehicle category, obstacles (fixed and mobile) using the dictionary defined in mapping.py (you can use the mapping.py file, but you can also create your own mappings).

In [78]:
from mapping import *
voiture["catV"] = voiture["catV"].map(info_vehicules)
voiture["obstacle_fixe"] = voiture["obstacle_fixe"].map(obstacle_fixe_labels)
voiture["obstacle_mobile"] = voiture["obstacle_mobile"].map(obstacle_labels)
print(voiture)

             Num_Acc  sens_de_Circulation                     catV  \
0       201600000001                  0.0                  VL seul   
1       201600000001                  0.0       Cyclomoteur <50cm3   
2       201600000002                  0.0                  VL seul   
3       201600000003                  0.0                  VL seul   
4       201600000004                  0.0  Scooter >50cm et<=125cm   
...              ...                  ...                      ...   
101919  201600059430                  1.0         Scooter < 50 cm3   
101920  201600059431                  2.0         Scooter < 50 cm3   
101921  201600059431                  1.0         Scooter < 50 cm3   
101922  201600059432                  1.0       Cyclomoteur <50cm3   
101923  201600059432                  2.0                  VL seul   

        nb_occupants                 obstacle_fixe obstacle_mobile  choc  \
0                  0                           NaN       inconnu_0   1.0   
1      

#### Heat Map - Vehicle Category vs Accident Moving Obstacle

25) Create a new database, projecting the category of the vehicle in relation to the moving obstacle.

The values of the data frame will be the sum of the respective occupant numbers.

This database can be referred to as a heat map of the number of accidents by type of transport and obstacle.

In [82]:
df = voiture.groupby(["catV", "obstacle_mobile"])[["nb_occupants"]].sum().reset_index()
df = df.pivot(index="catV", columns="obstacle_mobile", values="nb_occupants")
print(df)

obstacle_mobile                                     Animal domestique 6  \
catV                                                                      
Autobus                                                             NaN   
Autocar                                                             NaN   
Autre véhicule                                                     NaN   
Bicyclette                                                          0.0   
Cyclomoteur <50cm3                                                  0.0   
Engin spécial                                                      NaN   
Motocyclette                                                        0.0   
Motocyclette > 50 cm et <= 125 cm                                   0.0   
PL > 3,5T + remorque                                                NaN   
PL seul 3,5T <PTCA <= 7,5T                                          NaN   
PL seul > 7,5T                                                      NaN   
Quad                     

26) Using the previous results, obtain the most dangerous mode of transport for the public.

In [87]:
most = df.sum(axis=1).idxmax()
print(most)

Autobus


27) Sort the heatmap from the most dangerous to the least dangerous means of transport.

In [88]:
df.sum(axis=1).sort_values(ascending=False)

catV
Autobus                                                                                           2743.0
Tramway                                                                                           2547.0
Autocar                                                                                           1385.0
Train                                                                                              522.0
VU seul 1,5T <= PTAC <= 3,5T avec ou sans remorque (anciennement VU seul 1,5T <= PTAC <= 3,5T)       0.0
VL seul                                                                                              0.0
Tracteur routier seul                                                                                0.0
Tracteur routier + semi-remorque                                                                     0.0
Tracteur agricole                                                                                    0.0
Scooter >50cm et<=125cm                           

28) Get the most dangerous moving obstacle when using public tranpsortation.

In [90]:
mostpub = df.loc["Autobus":"Tramway"].sum(axis=0).sort_values().tail(1)
print(mostpub)

obstacle_mobile
Véhicule    3900.0
dtype: float64


29) Sort the heat map from the most dangerous to the least dangerous entity (means of transport, and moving obstacle)

In [93]:
print(df)
df.sum().sort_values()

obstacle_mobile                                     Animal domestique 6  \
catV                                                                      
Autobus                                                             NaN   
Autocar                                                             NaN   
Autre véhicule                                                     NaN   
Bicyclette                                                          0.0   
Cyclomoteur <50cm3                                                  0.0   
Engin spécial                                                      NaN   
Motocyclette                                                        0.0   
Motocyclette > 50 cm et <= 125 cm                                   0.0   
PL > 3,5T + remorque                                                NaN   
PL seul 3,5T <PTCA <= 7,5T                                          NaN   
PL seul > 7,5T                                                      NaN   
Quad                     

obstacle_mobile
Animal domestique 6       0.0
Animal sauvage            0.0
inconnu                   0.0
Véhicule sur rail        1.0
Autre                   138.0
inconnu_0              1247.0
Piéton                1911.0
Véhicule              3900.0
dtype: float64

In [102]:
df.to_csv("heatmap.csv")